<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <WarningsNotAsErrors>0612,0618</WarningsNotAsErrors>
    <PackageId>Avalonia.AvaloniaEdit</PackageId>
    <PackageDescription>This project is a port of AvalonEdit, a WPF-based text editor for Avalonia.</PackageDescription>
    <PackageTags>editor;code-editor;avalonia;text-editor;netstandard</PackageTags>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="**\*.xshd;**\*.resx;" Exclude="bin\**;obj\**;**\*.xproj;packages\**;@(EmbeddedResource)" />
    <AvaloniaResource Include="**\*.xaml;Assets\*;" Exclude="bin\**;obj\**;**\*.xproj;packages\**;@(EmbeddedResource)" />
  </ItemGroup>

  <ItemGroup Condition="'$(UseAvaloniaFork)' == 'False' OR '$(TargetFramework)' == 'net8.0'">
    <PackageReference Include="Avalonia" />
  </ItemGroup>

  <!-- iPlus settings and overrides -->
  <Import Condition="'$(UseAvaloniaFork)' == 'True' AND '$(TargetFramework)' == 'net10.0'" Project="../../../iPlus/build/AvaloniaInclude.props" />
  <!-- End iPlus settings and overrides -->
  
  <ItemGroup>
    <Compile Update="SR.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>SR.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="SR.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>SR.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
</Project>
