<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <PackageDescription>TextMate integration for AvaloniaEdit.</PackageDescription>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AvaloniaEdit\AvaloniaEdit.csproj" />
  </ItemGroup>

  <ItemGroup Condition="'$(UseAvaloniaFork)' == 'False' OR '$(TargetFramework)' == 'net8.0'">
    <PackageReference Include="Avalonia" />
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="TextMateSharp" />
    <PackageReference Include="TextMateSharp.Grammars" />
  </ItemGroup>

  <!-- iPlus settings and overrides -->
  <Import Condition="'$(UseAvaloniaFork)' == 'True' AND '$(TargetFramework)' == 'net10.0'" Project="../../../iPlus/build/AvaloniaInclude.props" />
  <!-- End iPlus settings and overrides -->


</Project>
